location /app {
        #root /home/jbochinski/coding_base/fl_bridges/bridge-reports/dist/bridge-reports/browser;
        

        proxy_pass http://unix:/home/magmek/magmek_site/aetherglow-ui/dist/aetherglow-ui/browser/index.html;

        # Pass original host, IP, and protocol headers to the backend
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        
        # Inform Flask about the URL prefix, crucial for url_for and redirects
        proxy_set_header X-Forwarded-Prefix /api/v1;
        
        # Prevent Nginx from rewriting Location headers from the backend
        proxy_redirect off;
        try_files $uri $uri/ =404;
    }