[program:magmek_backend]
command = /home/joseph/.cache/pypoetry/virtualenvs/magmek-backend-Fw4aPGVB-py3.12/bin/magmek-server --local
directory = /var/www/magmek_backend
user = joseph
stdout_logfile = /var/log/magmek_backend/stdout.log
stderr_logfile = /var/log/magmek_backend/stderr.log
autostart = True
autorestart = True