DROP TABLE IF EXISTS update_servers;
DROP TABLE IF EXISTS update_server;

CREATE TABLE update_server (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	url VARCHAR(255) NOT NULL,
	product_name VARCHAR(255) NOT NULL
);