server {
    listen 80;
    server_name companions-griffon-dore.com www.companions-griffon-dore.com;

    root /var/www/companions-griffon-dore.com;
    index index.html index.htm index.nginx-debian.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}