server {

    server_name wordpress.illuminated-artist.com;

    root /var/www/wordpress.illuminated-artist.com;
    index index.php index.html;

    client_max_body_size 64M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/wordpress.illuminated-artist.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/wordpress.illuminated-artist.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = wordpress.illuminated-artist.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name wordpress.illuminated-artist.com;
    return 404; # managed by Certbot


}

server {

    server_name piwigo.illuminated-artist.com www.illuminated-artist.com;

    root /var/www/piwigo.illuminated-artist.com;
    index index.php index.html;

    client_max_body_size 64M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;

        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/piwigo.illuminated-artist.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/piwigo.illuminated-artist.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot






}

server {
    if ($host = illuminated-artist.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = www.illuminated-artist.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = piwigo.illuminated-artist.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name piwigo.illuminated-artist.com www.illuminated-artist.com;
    return 404; # managed by Certbot






}