server {
    server_name www.magmek.io magmek.io;

    root /var/www/magmek.io;
    index index.html index.htm index.nginx-debian.html;


    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 80;
}