server {
    server_name trutrafik.magmek.io;

    root /var/www/trutrafik.io;
    index index.html index.htm index.nginx-debian.html;


    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 80;

}