[program:griffons-poller]
command = /home/magmek/.cache/pypoetry/virtualenvs/griffons-backend-Cr33xM30-py3.12/bin/griffons-poller
directory = /var/www/griffons-backend
user = magmek
group = www-data
stdout_logfile = /var/log/griffons-poller/stdout.log
stderr_logfile = /var/log/griffons-poller/stderr.log
autostart = True
autorestart = True