[program:sl_api]
command = /home/magmek/.cache/pypoetry/virtualenvs/magmek-backend-ltLPWtng-py3.12/bin/magmek-sl-api 
directory = /var/www/magmek_backend
environment=\
SL_SHARED_SECRET="881da95c-b462-4ec6-a7d3-82f1d359d238",SL_AUTH_TS_SKEW_SECONDS="90",SL_AUTH_NONCE_TTL_SECONDS="300",SL_LOGIN_CODE_TTL_SECONDS="60"
user = magmek
group = www-data
stdout_logfile = /var/log/sl_api/stdout.log
stderr_logfile = /var/log/sl_api/stderr.log
autostart = True
autorestart = True