[program:sl_api]
command = /home/magmek/.cache/pypoetry/virtualenvs/magmek-backend-ltLPWtng-py3.12/bin/magmek-sl-api 
directory = /var/www/magmek_backend
environment = SL_SHARED_SECRET=%(SL_SHARED_SECRET)s,SL_AUTH_TS_SKEW_SECONDS=%(SL_AUTH_TS_SKEW_SECONDS)s,SL_AUTH_NONCE_TTL_SECONDS=%(SL_AUTH_NONCE_TTL_SECONDS)s,SL_LOGIN_CODE_TTL_SECONDS=%(SL_LOGIN_CODE_TTL_SECONDS)s,REDIS_URL=%(REDIS_URL)s
user = magmek
group = www-data
stdout_logfile = /var/log/sl_api/stdout.log
stderr_logfile = /var/log/sl_api/stderr.log
autostart = True
autorestart = True