[program:liquid_tof]
command = /usr/bin/liquidsoap /var/www/stream/scripts/tof_playlist.liq
directory = /var/www/stream/
user = magmek
group = www-data
stdout_logfile = /var/log/liquid_tof/stdout.log
stderr_logfile = /var/log/liquid_tof/stderr.log
autostart = True
autorestart = True